/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 demon_skull.glb -T 
Files: demon_skull.glb [4.86MB] > /home/voz/Coding/demo_Port/public/models/demon_skull-transformed.glb [447.93KB] (91%)
Author: Auxiar Molkhun (https://sketchfab.com/AuxiarMolkhun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/demon-skull-0cb0efd8bd8a405f89ce5f757ecf6e8d
Title: Demon Skull
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function DemonModel(props) {
  const groupRef = useRef();
  
  const { nodes, materials } = useGLTF("/models/demon_skull-transformed.glb");



  
   useFrame((state) => {
    if (!groupRef.current) return;
    const t = state.clock.elapsedTime;

    // Float up and down
    groupRef.current.position.y = Math.sin(t * 2) * 0.045;

    // Head rotation (spooky, slow, natural)
    const spookyRotation = Math.sin(t * 0.6) * 0.3; // side-to-side tilt
    const slightNod = Math.sin(t * 0.8) * 0.05; // tiny up-down movement
    groupRef.current.rotation.y = spookyRotation; // look left-right
    groupRef.current.rotation.x = slightNod;   
    });
  
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <pointLight
        position={[-0.4, 0, 0]} // tweak slightly forward from eyes
        intensity={8}
        color="#ff0000"
        distance={3}
      />

      <pointLight
        position={[-4.08, 10.95, 12.15]} // tweak slightly forward from eyes
        intensity={8}
        color="#ff0000"
        distance={3}
      />

     
      {/* <mesh position={[4.08, 10.95, 12.15]}>
        <sphereGeometry args={[1.5, 16, 16]} />
        <meshStandardMaterial
          emissive="#ff0000"
          emissiveIntensity={50}
          color="black"
        />
      </mesh> */}

      {/* <mesh ref={leftEye} position={[-4.08, 10.95, 12.15]}>
        <sphereGeometry args={[1.5, 16, 16]} />
        <meshStandardMaterial
          emissive="#ff0000"
          emissiveIntensity={50}
          color="red"
        />
      </mesh> */}
      <mesh
        castShadow
        geometry={nodes.DemonSkull_DemonSkull_0.geometry}
        material={materials.DemonSkull}
        position={[0, 1.927, -0.007]}
        material-roughness={1}
      />
    </group>
  );
}

useGLTF.preload("/models/demon_skull-transformed.glb");
